### PR TITLE
nsc-events-android_2_201_drop-down-menu

### LINKED ISSUE #201: Nav Bar: Drop Down Menu
As a developer, I'd like the hamburger button in the nav bar to have a drop down menu, with sign up and login links.

Related to User Story #200

### PR DESCRIPTION
**Pull request by intisarosman1**
Resolves #201 

I added a dropdown menu to the hamburger button with sign up and login links as the menu items. The menu items redirect to their relevant pages.

Screenshot 2024-02-12 001644

Part of User Story #200

### CODE REVIEW

**Review by heosman — APPROVED** [review]
Good job, the sign up link routes to the sign up page and the login button routes to the sign in page.

**Review by taylorpapke — APPROVED** [review]
Looks good and is routing to the sign up and login page. I guess my only feedback would be for @heosman because I'm not so sure about the design. Mainly because of the link to the sign up page. I was kind of thinking that sign up would be done through the login page as an option for if you didn't have an account already. Also, if you accidentally click the sign up page, you have to go back twice to get to the home page again. 

Anyways, we can discuss more about this later. The other thing I'm thinking about is once a user signs in. Will the hamburger menu options switch to display a link to the admin/creator page and a link to sign out?

**Comment by heosman** [comment]
> Looks good and is routing to the sign up and login page. I guess my only feedback would be for @heosman because I'm not so sure about the design. Mainly because of the link to the sign up page. I was kind of thinking that sign up would be done through the login page as an option for if you didn't have an account already. Also, if you accidentally click the sign up page, you have to go back twice to get to the home page again.
> 
> Anyways, we can discuss more about this later. The other thing I'm thinking about is once a user signs in. Will the hamburger menu options switch to display a link to the admin/creator page and a link to sign out?

@taylorpapke I see what you mean about the sign up button in the nav bar being redundant so maybe we should remove it in another issue later. I was wondering about the hamburger menu too. After an admin/creator user signs in, and they press any of the options on the admin/creator view, they won't be able to go back to that page to access those options again. I was thinking that there should there be a button on the nav bar that can bring you back to that page which would only be visible to admins/creators (like a "dashboard" button). And of course, a sign out button for all users, when signed in.

**Comment by taylorpapke** [comment]
> > Looks good and is routing to the sign up and login page. I guess my only feedback would be for @heosman because I'm not so sure about the design. Mainly because of the link to the sign up page. I was kind of thinking that sign up would be done through the login page as an option for if you didn't have an account already. Also, if you accidentally click the sign up page, you have to go back twice to get to the home page again.
> > Anyways, we can discuss more about this later. The other thing I'm thinking about is once a user signs in. Will the hamburger menu options switch to display a link to the admin/creator page and a link to sign out?
> 
> @taylorpapke I see what you mean about the sign up button in the nav bar being redundant so maybe we should remove it in another issue later. I was wondering about the hamburger menu too. After an admin/creator user signs in, and they press any of the options on the admin/creator view, they won't be able to go back to that page to access those options again. I was thinking that there should there be a button on the nav bar that can bring you back to that page which would only be visible to admins/creators (like a "dashboard" button). And of course, a sign out button for all users, when signed in.

Yeah, maybe we could use this icon or something like it:
3f9470b34a8e3f526dbdb022f9f19cf7

**Pull request merged**
