### PR TITLE
Ci branch strategy compliance

### PR DESCRIPTION
**Pull request by theGaryLarson**
As an Automation Developer I want to ensure that there is an enforced branching strategy and CI/CD setup across the project repositories.
<hr></hr>
Hey this is kind of a large PR but I did test it in a forked version of the repo to ensure it is working.

### SUMMARY
Any pushes/merges into main will trigger a merge into STAGING
CI has to pass before merge will happen.
Level of redundancy for safety. e.g. On a PR CI is called when a new branch is created CI is called when a branch is merged into main CI is called again before merging to  STAGING.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
LGTM

**Review by Seiyaroo — DISMISSED** [review]
So do we wanna test this live eventually? You and I can meet Monday / Tuesday if you want and do a live run of this just to make sure. Do some kind of small change in CSS or something.

Either way, LGTM! But definitely think we should run a live version of it, or perhaps a demo of it during our PM/PO meeting this week if we wanna save time and do less meetings.

**Comment by Seiyaroo** [comment]
Going to wait for @brandondombrowsky to review, but if / when you do Brandon you can be the merge person :P

**Comment by theGaryLarson** [comment]
@Seiyaroo It works Taylor and I were working on it in a forked "sandbox" to confirm. I didn't get the merging working until later but I posted the successful workflow log in Slack.  I would love to get together and do a demo. 

Any changes that have been pushed to main will merge into staging on a successful CI check. Now the important thing is enforcing the creation of tests to add to the tests folder. This being successful in the long run really depends on devs writing tests for their code and running them prior. As well as including them with the PR.

**Review by taylorpapke — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]

**Review by bcko — APPROVED** [review]
LGTM

**Pull request merged**
