### PR TITLE
nsceventsandroid_sprint5_226_removesignup

### LINKED ISSUE #226: Nav Bar: Remove sign up link from nav bar
Relates to #212 
This issue is for removing the sign up link from the nav bar.

Image

### PR DESCRIPTION
**Pull request by MaddasaHatter**
Resolves #226 
This PR removes the signup link from the navigation menu.

Screenshot 2024-04-16 201042

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
LGTM

**Review by Robel-003 — APPROVED** [review]
Looks good. I only see the login option just like your screenshot

**Comment by MuhammadNSC** [comment]
I checked out he branch and the bug changed is fixed. I don't see the sign up page in the navbar from my end. Code looks good.

**Comment by nhapham03** [comment]
I cloned it to my local device and it looks good!

**Pull request merged**
