### PR TITLE
nsc-events-android-5-229-add-sign-out-button

### LINKED ISSUE #229: Should be added to the nav bar after user has logged in

### PR DESCRIPTION
**Pull request by nhapham03**
Resolves #229

### CODE REVIEW

**Review by LilithLucifer3x6 — DISMISSED** [review]
Looks good to me. It functions as I would epect.

**Comment by heosman** [comment]
@nhapham03 I do not see any changes in the files for this PR.

@Robel-003 Not sure why that image was shown, but this PR should be for the android app.

**Comment by MuhammadNSC** [comment]
I dont see this changes in the NSC android app. The image shown shows that the sign-out function was done to the NSC nextjs app

**Comment by JesseCaddell** [comment]
closing due to lack of engagement. 5 month old PR.

**Pull request closed without merging**
