### PR TITLE
Nsc-events-android-223-create-event-page-fields-update-01

### PR DESCRIPTION
**Pull request by Robel-003**
Resolves user story #223 and issue #224 

This PR ensures that the fields in the create event page are caught up with the backend and database. It fixes the event tags by switching them to button options from text fields. It also addresses the appearance of the fields in this page by making it consistent with the web application 

Screenshot 2024-04-15 at 5 17 29 PM

Screenshot 2024-04-15 at 5 23 58 PM

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks good and Is working on my end. 
Screenshot 2024-04-17 at 12 44 09 AM
I was curious about 1 thing and that is regarding the upload event image photo picker because there is also a field for the event cover photo below it which just takes an image link. Is the plan to eventually just have the photo picker once it is able to save the photos? @heosman 

@MaddasaHatter @keiffer213 Please review this if you get a chance.

**Review by heosman — CHANGES_REQUESTED** [review]
@Robel-003 The task of adding tags is missing from your user story. I'm not sure if you will address it in this PR or create another issue, but could you do the following:

- Add Event Meeting URL text field
- Add these event tags: Art/Creative, Conference, Craft, Pizza, Free Food, LGBTGIA
- Also, to avoid confusion and be consistent, change "Event name" to "Event title"

@taylorpapke Yes, that's the plan. It's temporary because at the moment, it is difficult to upload photos using the emulator.

**Comment by Robel-003** [comment]
> @Robel-003 The task of adding tags is missing from your user story. I'm not sure if you will address it in this PR or create another issue, but could you do the following:
> 
> * Add Event Meeting URL text field
> * Add these event tags: Art/Creative, Conference, Craft, Pizza, Free Food, LGBTGIA
> * Also, to avoid confusion and be consistent, change "Event name" to "Event title"
> 
> @taylorpapke Yes, that's the plan. It's temporary because at the moment, it is difficult to upload photos using the emulator.

@heosman I'll address the missing tags on this PR and add those additional tags, as well as fixing those changes you suggested.

**Review by heosman — APPROVED** [review]

**Comment by heosman** [comment]
Looks good! I was able to create an event successfully with the new changes.

image

**Review by intisarosman1 — APPROVED** [review]
Looks as it should; all the fields are there and the event tags are selectable buttons.
Screenshot 2024-04-24 000852

**Pull request merged**
