### PR TITLE
Home Page Addition #29

### LINKED ISSUE #29: Home Page Addition
As a Developer, I want to make sure my client has a "home" page for their mobile app. For now we only have login, so I want to make sure that we also have that "home" or "landing" page as well.

Story Points: 3-6

### PR DESCRIPTION
**Pull request by Robel-003**
resolve #29 

Added a skeletal home page that routes to the sign-in/add events page. Home page is bare bones so any feedback on layout would be greatly appreciated. From those pages, you can go back to home page. 

Screenshot 2023-08-22 at 12 43 31 PM

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Tested it and it is working as expected. Great job on this! The app is really coming together well!

**Comment by brinkbrink** [comment]
Bare bones is all that is needed! We are not making a complete product this summer, we are making a minimally viable product (MVP) for us/other students to continue working on this upcoming academic year. So don't sweat it being "skeletal," this is perfect! Thank you, Robel!

**Review by brinkbrink — CHANGES_REQUESTED** [review]
Bare bones is all that is needed! We are not making a complete product this summer, we are making a minimally viable product (MVP) for us/other students to continue working on this upcoming academic year. So don't sweat it being "skeletal," this is perfect! Thank you, Robel!

As far as not passing CI I noticed on Slack that Tin had a problem, too, that Gary helped him work on. Maybe check out that conversation and see if the same issue applies here (Android Studio had converted png to jpeg). If that's not the issue maybe @theGaryLarson can help you figure out what is.

**Review by brinkbrink — APPROVED** [review]

**Comment by brinkbrink** [comment]
Hey @Robel-003 can you try adding an empty commit to this PR to re-trigger the CI? From what I've been reading sometimes this just happens and sometimes it just works after triggering it again. Just something simple to try.

**Pull request merged**
