### PR TITLE
nsc-events-android-3-81-create_input_fields 

### PR DESCRIPTION
**Pull request by Exochos**
Started work on events pages, added various functionality such as a date + time picker.

### CODE REVIEW

**Comment by Exochos** [comment]
eventPage-Default
eventPage-Errors
eventPage-Filled

**Review by kkennedy-gh — APPROVED** [review]
The scrollable list implementation is good. The UI layout is also user-friendly. The image upload functions are something I need to learn also.

**Comment by taylorpapke** [comment]
Amazing!

**Review by taylorpapke — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]

**Comment by tinpham5614** [comment]
A few conflicts need to be resolved.

**Review by brandondombrowsky — APPROVED** [review]
I like this. I think it added value to the app. I can't wait til the UI catches up with our team's improvements.

**Review by taylorpapke — APPROVED** [review]
Looks great! Thanks for fixing the merge conflicts and getting this feature working!

**Review by bcko — APPROVED** [review]
Great job on fixing the merge conflicts and lint errors!

**Pull request merged**
