### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by taylorpapke**
Enabled dependabot on repo and added yaml file to check gradle dependencies daily.

### CODE REVIEW

**Review by brandondombrowsky — DISMISSED** [review]
LGTM

**Review by brinkbrink — APPROVED** [review]
My only comment is to change interval to weekly like you've done with Belinda's.

**Review by brinkbrink — APPROVED** [review]
LGTM, thanks!

**Review by Seiyaroo — APPROVED** [review]
LGTM

**Pull request merged**
