### PR TITLE
nsc_events_android-187-creating_an_event

### PR DESCRIPTION
**Pull request by Robel-003**
Relates to this user story #186 and #[70](https://github.com/SeattleColleges/nsc-events-nestjs/issues/70) and closes this issue #187 and #[71](https://github.com/SeattleColleges/nsc-events-nestjs/issues/71)

frontend and backend integration. Making a POST call to create an event in the add event page. At the moment, it’s not properly doing any validation checks but that will be the next step.

To test:
- Run the backend locally (it might throw an error if eventCategory in the backend activity create dto is set to _@IsNotEmpty_, so temporarily change that to _@IsOptional_)
- Start up the android app and login from the home page. Navigate to the create event page 
- Fill in all the fields then click “add event” (eventCoverPhoto and eventWebsite must be a url address, eventContact must be an email, eventCapacity must be a number) 
- Check the logcat to see the logging details and/or check mongodb to see the newly created event   

Here's a walkthrough [demo](https://www.youtube.com/watch?v=klmqFgcz_Sw) of the event creation process

### CODE REVIEW

**Comment by Seiyaroo** [comment]
@Robel-003 Did we still want to keep this open or close this out?

**Comment by Robel-003** [comment]
> @Robel-003 Did we still want to keep this open or close this out?

@Seiyaroo we can close this out. Doesn't need to be merged at the moment, still a work in progress

**Comment by kaimanasse15** [comment]
https://youtu.be/HsUxkJ3yBTQ link check video

**Comment by taylorpapke** [comment]
@Robel-003 what is the status of this? Did we want to review and try to merge this?

**Review by taylorpapke — APPROVED** [review]
Nice work! I was able to add an event but had to follow your instructions and change the following line from @IsNotEmpty() to @IsOptional():
Screenshot 2024-01-16 at 2 24 21 AM
After entering the correct values into the other 4 fields you mentioned, I was able to add an event and view it in my MongoDB database:
Screenshot 2024-01-16 at 2 17 56 AM
I think we should create a user story with 2 issues. 1 issue for this PR and another issue for the nsc-events-nestjs repo so we can change that 1 line above.

**Comment by Robel-003** [comment]
> Nice work! I was able to add an event but had to follow your instructions and change the following line from @isnotempty() to @IsOptional():
> Screenshot 2024-01-16 at 2 24 21 AM
> After entering the correct values into the other 4 fields you mentioned, I was able to add an event and view it in my MongoDB database:
> Screenshot 2024-01-16 at 2 17 56 AM
> I think we should create a user story with 2 issues. 1 issue for this PR and another issue for the nsc-events-nestjs repo so we can change that 1 line above.

@taylorpapke I've created the user story and issues for this pr and assigned it to this pr. If it all looks good, I can go head and merge this to main

**Comment by taylorpapke** [comment]
@SeattleColleges/leadership Can we get another review on this when someone gets a chance. Would like to get this merged in before we resume work on android next sprint.

**Review by bcko — APPROVED** [review]
LGTM

**Pull request merged**
