### PR TITLE
Product functionality added

### LINKED ISSUE #20: Add a product functionality (UI)
As a web/android UI developer, I will want to create the UI for add a product functionality.

Is your feature request related to a problem? Please describe.
Users need a user interface to add products to their inventory.

Describe the solution you'd like
Create a user interface for adding a product.

Story Points
4-10

### PR DESCRIPTION
**Pull request by Robel-003**
Resolve #20 

- Implemented product functionality to add events based on event, event description, and event date. (Can add more fields if necessary)
- From login page, user can navigate to event page to add an event. Ideally, once user logins in, the event page should appear instead of it showing on login page.
- User can input event details but eventually should store event into an inventory or database

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Tested it and is working as expected. Looks like code factor check failed because of the TODO's but not sure why.

**Review by Seiyaroo — APPROVED** [review]
LGTM

**Comment by Seiyaroo** [comment]
> Tested it and is working as expected. Looks like code factor check failed because of the TODO's but not sure why.

It looks like CodeFactor is simply limiting TODO's since they're not supposed to be in production code, in theory. Or his Markdown is "incorrect" but I don't think it's a major issue right now.

**Comment by theGaryLarson** [comment]
Correct, CodeFactor is strict I will  see about modifying CodeFactor here soon so its not so strict. It sees TODOs as unfinished business so flags it. Still good just to look at the details to be sure. @Seiyaroo you were able to view them?

**Comment by taylorpapke** [comment]
Should we go ahead and merge this one?

**Review by Seiyaroo — APPROVED** [review]
No visible conflicts, LGTM

**Pull request merged**
