### PR TITLE
nsc-events-android-1-50-delete-functionality

### LINKED ISSUE #50: UI - Enable Soft Delete Product functionality
**NOTE** 
_We are going to leave "Product" here as its relevant to the pictures provided, but note that PRODUCT in this case, means EVENT for NSC._

**Describe the bug**\
Deleting a product in the UI does not make the product disappear from the UI. Enable Soft Delete Product functionality--make product disappear from client side (do not worry about the database) after clicking "Yes".

**To Reproduce**\
1. Go to the product list page.
2. Click on the pencil icon in the top right corner of the screen
3. Click a trashcan icon below any product.
4. Click "Yes" in the pop-up message
5. Notice that the product is still visible.

**Expected behavior**
1. Go to the product list page.
2. Click on the pencil icon in the top right corner of the screen
3. Click a trashcan icon below any product.
4. Click "Yes" in the pop-up message
5. You should then be taken back to the product list page and the product with the trashcan icon you clicked should no longer be visible.

**Screenshots**

screenshot_2023-10-03_at_3 47 54___am_480-1

You can also observe the current behavior in this [demo on YouTube](https://www.youtube.com/shorts/M5jzwP3tuek).

**Additional context**\
This is only concerning the client side behavior and UI. This does not involve deleting the product from the database.

**Resources and Tutorials**

[Jetpack Compose Tutorial](https://developer.android.com/jetpack/compose/tutorial)
[Geeks for Geeks on buttons in Kotlin](https://www.geeksforgeeks.org/button-in-kotlin/)
[Medium article on Routes in Android Studio](https://medium.com/swlh/navigate-between-activities-in-android-studio-c7f4617e7388)

**Story Points**\
4-8

### PR DESCRIPTION
**Pull request by TroyFPV48**
resolve #50

### CODE REVIEW

**Comment by taylorpapke** [comment]
@Seiyaroo @Robel-003 @theGaryLarson I'm a little confused about this issue #50 as it's not viewable anywhere in the nsc-events kanban board yet here it is as well as linked through user story #54. Anyways, I'm not sure if the app has progressed to the point yet where issue #50 should be worked on quite yet since the product pages aren't quite functional on the frontend. Would it be better to wait until those pages get merged in and do a fresh pull from main before continuing on this issue?

**Comment by Robel-003** [comment]
> @Seiyaroo @Robel-003 @theGaryLarson I'm a little confused about this issue #50 as it's not viewable anywhere in the nsc-events kanban board yet here it is as well as linked through user story #54. Anyways, I'm not sure if the app has progressed to the point yet where issue #50 should be worked on quite yet since the product pages aren't quite functional on the frontend. Would it be better to wait until those pages get merged in and do a fresh pull from main before continuing on this issue?

I think @theGaryLarson might have a better answer. But yeah I do agree, this functionality should later be fully implemented once there's a connection to the backend. I think getting the button set up right now would help though

**Review by Robel-003 — APPROVED** [review]
I don't see the delete button anywhere in the add events page. I think you would need to incorporate a DeleteButton composable within the AddEventPage composable.

**Review by theGaryLarson — APPROVED** [review]
Overall, looks good. Just an FYI for boolean values it is good to prefix them with the word is. So instead of eventVisibility use isVisible. This signals that it is a yes no value. Other than that looks good.

**Comment by theGaryLarson** [comment]
> I don't see the delete button anywhere in the add events page. I think you would need to incorporate a DeleteButton composable within the AddEventPage composable.

The delete button is created but not part of anything yet. So when we have it working it is just a matter of including the Delete button composable. Rather than creating it from scratch

**Comment by TroyFPV48** [comment]
yes, i can just change it from eventVisibility into isVisible then.

**Pull request merged**
