### PR TITLE
nsc-events-android_5_233_add-pronouns-field 

### LINKED ISSUE #233: Sign up Page: Add pronouns field
- Relates to #231 
- I plan to add a pronoun field during the sign-up process.
- Make sure frontend is caught up with the backend

### PR DESCRIPTION
**Pull request by MaddasaHatter**
Resolves #233 
This PR adds a pronouns field to the sign-up page
https://github.com/SeattleColleges/nsc-events-android/assets/52189566/c32cd6b5-4eb6-4220-9d0d-87791a0faecf

Remember to:
Add reviewers

### CODE REVIEW

**Comment by taylorpapke** [comment]
@tinpham5614 How would we go about connecting the frontend to the backend for android?

**Comment by tinpham5614** [comment]
> @tinpham5614 How would we go about connecting the frontend to the backend for android?

Are you referring to the implementation or running the app for testing?
For the implementation, I don't have an instruction but official documentation.
Here is the [link](https://www.notion.so/Android-development-resources-878383c32a074efd81855a6fbad53d83)
For testing, we just run the Android app and backend NestJs the same as the web version.

**Review by taylorpapke — APPROVED** [review]
@tinpham5614 Thanks! Yes, I was referring to the implementation. It appears that you can login and possibly create events but it still shows sample events and users.

@MaddasaHatter Looks good to me! I am seeing the pronouns field and am able to enter text including numbers and special characters:
Screenshot 2024-04-30 at 3 35 13 AM

**Review by heosman — APPROVED** [review]
LGTM!

**Comment by brinkbrink** [comment]
Because this is for the android and we don't expect folks from the junior cohort to interact with this repo I am merging without waiting for a 3rd review to be made since this more than fulfills the old requirements, with 2 approvals, 2 coming from leadership.

**Pull request merged**
