### PR TITLE
nsc_android_feature_147_adminviewpage

### LINKED ISSUE #147: Admin View Page: Create an Admin View page
Relates to user story: #95 

- Create a Edit User Role button, routing admin to a separate page (Edit User View) allowing them to give user(s) certain permissions

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves #147 and #95

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
Please create a temp admin button on home page above creator view and make sure that edit role button is inactive but doesn't crash app (currently redirecting to create event page). Good other than that.

**Comment by taylorpapke** [comment]
@Ali-7s What's the status on this PR?

Also, I added tags on the right sidebar for this and changed the PR title to match our naming convention. Please make sure to do this next time 🙂

**Review by taylorpapke — APPROVED** [review]

**Comment by taylorpapke** [comment]
We just have some merge conflicts to resolve on this one but they are not bad.

**Comment by taylorpapke** [comment]
@SeattleColleges/leadership We need 1 more approval here. Also, @Ali-7s do you need assistance with the merge conflicts?

**Comment by Ali-7s** [comment]
> @SeattleColleges/leadership We need 1 more approval here. Also, @Ali-7s do you need assistance with the merge conflicts?

Hey, yeah. How do fix merge conflicts?

**Comment by brinkbrink** [comment]
@Ali-7s [This link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) may help!

**Review by brinkbrink — APPROVED** [review]
Looks like you've got this to a good place but need to sort out the merge conflicts. Check out my other comment for a helpful link.

**Comment by Ali-7s** [comment]
> Looks like you've got this to a good place but need to sort out the merge conflicts. Check out my other comment for a helpful link.

Hey, I just fixed and was wondering is it possible to sign old commits?

**Comment by taylorpapke** [comment]
@Ali-7s Signing old commits is difficult. I will override and merge this PR since it has 2 approvals.

**Pull request merged**
