### PR TITLE
Nsc events android 3 97 edit button

### PR DESCRIPTION
**Pull request by Exochos**
Added a new screen Event edit which leads off of the eventDetail page. Of note is the screen doesn't do anything with the save button yet. Nor did I add functionality to edit the image.  Also of note that the event model has a lot more fields I didn't account for, but that is all in flux so I was told to hold off of implementing all of that for now.

https://github.com/SeattleColleges/nsc-events-android/assets/35015441/fea3748c-eaf0-48ca-9bb3-0f470a4a06cd

### CODE REVIEW

**Comment by taylorpapke** [comment]
@Exochos Is this PR ready for review?

**Review by taylorpapke — APPROVED** [review]
Looks great! One thing I noticed is that since there is no scroll, you can't reach the save button if the description is too long. Everything else seems to be working fine.

**Comment by theGaryLarson** [comment]
update with changes from main and ensure everything works as expected.

**Comment by bcko** [comment]
> Looks great! One thing I noticed is that since there is no scroll, you can't reach the save button if the description is too long. Everything else seems to be working fine.

Let's merge this and address a long description issue in a separate pull request after we handle other higher priority issues

**Pull request merged**
