### PR TITLE
Feature backend connection

### PR DESCRIPTION
**Pull request by theGaryLarson**
@tinpham5614 When you have time this evening can we discuss some things regarding http connection. I am having some issues which i commented on in the code. I am hoping you can help me work through it.

### CODE REVIEW

**Comment by theGaryLarson** [comment]
Odd its not authenticated.
image

**Comment by bcko** [comment]
@tinpham5614 @theGaryLarson let's get this wrapped up.

**Comment by tinpham5614** [comment]
@theGaryLarson Are you working on this? If not, I can work on this issue. I just want to avoid duplicating work.

**Comment by theGaryLarson** [comment]
> @theGaryLarson Are you working on this? If not, I can work on this issue. I just want to avoid duplicating work.

@tinpham5614 If you can that would be great!

**Comment by tinpham5614** [comment]
This pull request will be redirected to #127. To avoid confusion, I will close it.

**Pull request closed without merging**
