### PR TITLE
nsc-events-android_5_215_misc-tasks-admin-page

### PR DESCRIPTION
**Pull request by kaimanasse15**
I simply changed the onClick action of the "View Events" button to navigate to the Home Page using navController.navigate(Routes.HomePage.route)

### CODE REVIEW

**Comment by taylorpapke** [comment]
@heosman @kaimanasse15 So I think there is a little bit of a problem with the requirements here. According to the Miro board, admin page should route "view all events" page to the home page but there is only a "view events" page and It already routes to the home page. This PR only adds a line of white space which is not necessary:
Screenshot 2024-04-16 at 12 56 50 PM

In regards to this specific task, @heosman would you prefer that @kaimanasse15 changes the title of "view events" to "view all events"? Also, how about the "view my events" button? Is this a button link you would like to include since this is an option in the creator page?

**Comment by heosman** [comment]
> @heosman @kaimanasse15 So I think there is a little bit of a problem with the requirements here. According to the Miro board, admin page should route "view all events" page to the home page but there is only a "view events" page and It already routes to the home page. This PR only adds a line of white space which is not necessary: Screenshot 2024-04-16 at 12 56 50 PM
> 
> In regards to this specific task, @heosman would you prefer that @kaimanasse15 changes the title of "view events" to "view all events"? Also, how about the "view my events" button? Is this a button link you would like to include since this is an option in the creator page?

@taylorpapke Yes, I was unable to update the Miro Sprint planning board, but I did mention this in @kaimanasse15's [user story](https://github.com/SeattleColleges/nsc-events-android/issues/214) and [issue](https://github.com/SeattleColleges/nsc-events-android/issues/215) for the admin page. All that needs to be done for this user story is changing the text of the "View Events" button on the admin page to "View All Events". I included the task of adding the "View my Events" button on the admin page to the View My Events page user story, rather than for this user story.

**Comment by nhapham03** [comment]
Your code looks good to me.

**Comment by heosman** [comment]
@kaimanasse15 To avoid confusion, I will be converting this PR to a draft. Please open for review once you've made progress.

**Comment by kaimanasse15** [comment]
I thought that Nick already checked it with me and merge on the main? I think it is another pull request.

**Comment by heosman** [comment]
> I thought that Nick already checked it with me and merge on the main? I think it is another pull request.

@kaimanasse15 I mean the task of changing the text of the "View Events" button on the admin page to "View All Events". I do not see this reflected on the main branch. Have you been working on this task? If you plan to open another pull request addressing this issue, I'll go ahead and close this PR.

**Comment by kaimanasse15** [comment]
Yes! Please help me to close it because I worked on it in the other pull request already. I don’t know why nothing has changed.

**Comment by heosman** [comment]
> Yes! Please help me to close it because I worked on it in the other pull request already. I don’t know why nothing has changed.

@kaimanasse15 Can you send me that PR on Slack so we can work this out? I'll close this PR, but from what I'm seeing, there have been no changes, so this issue has not been completed.

**Pull request closed without merging**
