### PR TITLE
nsc-events-android-2-75-create-edit-delete-attend-buttons

### PR DESCRIPTION
**Pull request by taylorpapke**
- still needs tests
- branch created off of PR #64 and will need to be updated with main if/when it gets merged in

resolves: #75 

Screenshot 2023-10-20 at 10 14 37 AM

### CODE REVIEW

**Review by Robel-003 — COMMENTED** [review]
This looks really good! I'm able to view each event after clicking it. Really like the event details and images. Great job!

**Review by theGaryLarson — APPROVED** [review]
Looks good! Nice work creating some events to load in as an example until we get the backend connected. Also great work on adding some tests.

**Review by Robel-003 — APPROVED** [review]
It says the resolved conflicts are too complex to do in here, when you get a chance can you resolve those conflicts and I'll merge this into main

**Comment by taylorpapke** [comment]
> It says the resolved conflicts are too complex to do in here, when you get a chance can you resolve those conflicts and I'll merge this into main

@Robel-003 I created a separate fix PR #103 that I believe should start to help with some of these conflicts.

**Pull request closed without merging**
