### PR TITLE
adding ci pipeline

### PR DESCRIPTION
**Pull request by taylorpapke**
-added ci.yml
-added main.yml and pull-request.yml
-added kover to build.gradle for code coverage
-added additional unit test

This addition should help keep the style of our ci/cd systems similar in both our web and mobile repos. This uniform approach should help add a sense of familiarity/simplicity to whomever navigates these file structures at a later time.

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
So we're affirming here that we're maintaining a bare minimum of 33 on the SDK correct? and compose is staying in ver 1.7.2? 

If so, LGTM

**Comment by bcko** [comment]
Let's try to keep both Belinda's Closet Android and NSC Events Android app's sdk requirements the same. 
https://github.com/SeattleColleges/belindas-closet-android/blob/main/app/build.gradle#L8L13
Here is @tinpham5614 's reasoning for changing from 33 to 34
https://github.com/SeattleColleges/belindas-closet-android/pull/6#discussion_r1241493778

**Review by bcko — APPROVED** [review]

**Comment by bcko** [comment]
Let's merge this pull request before merging any dependabot pull requests. Once this pull request gets merged, we want to trigger this test on dependabot pull requests.

**Comment by tinpham5614** [comment]
@bcko
I just noticed:
In Belinda's Closet app, I used: `implementation "androidx.compose.material3:material3:1.2.0-alpha03"`  requires SDK 34.
In the NSC app: `implementation "androidx.compose.material3:material3:1.1.1"`, works fine with SDK 33 or 34.
`1.2.0-alpha03` is the newest and `1.1.1` is a stable version.
I should have clarified which version we use before implementing it.

**Pull request merged**
