### PR TITLE
nsc-event-android-2-67-Homepage-UI

### LINKED ISSUE #67: USER STORY: Home Page UI
As a user I want to ensure the home page routes to the User View (default page). Please see diagram below.

- [x] #105

Resource:
https://m3.material.io/

NSC1

- [ ] Specific Issue: I would like better visuals for the heading and font. Find something accessible, and not hard to read. Get it working in the app.
- [ ] Specific issue: I would like to create a sign-up and sign-in button and add it to the navbar. These buttons should have functionality routing users to their respective pages. 
~- [ ] Specific issue: I would like to create Event Card(s) depending on how many events there currently are. The event card needs minimal input fields such as title and date. The event cards need functionality routing user to the Events Detail View page~

### PR DESCRIPTION
**Pull request by TroyFPV48**
resolves #67

### CODE REVIEW

**Review by Robel-003 — DISMISSED** [review]
I'm getting an error when attempting to run the code. It's coming from this page. I think since you added eventVisibility in the Event data class, the line where the error is thrown is expected a boolean value for the eventVisibility parameter

Screenshot 2023-10-27 at 3 42 30 PM

**Comment by Robel-003** [comment]
> I'm getting an error when attempting to run the code. It's coming from this page. I think since you added eventVisibility in the Event data class, the line where the error is thrown is expected a boolean value for the eventVisibility parameter
> 
> Screenshot 2023-10-27 at 3 42 30 PM

you can disregard my comment. I just noticed you fixed this in a later pr

**Comment by taylorpapke** [comment]
@TroyFPV48 What's the status of this PR? If it is ready, I think we should resolve the conflicts and mark it as ready for review.

Here's a helpful doc for resolving conflicts just in case:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by TroyFPV48** [comment]
sorry the recent commit was supposed to be pushed on another branch for issue 50, please ignore this code for now.

**Comment by taylorpapke** [comment]
> sorry the recent commit was supposed to be pushed on another branch for issue 50, please ignore this code for now.

@TroyFPV48 Should we revert this back to a draft? Will you continue to work on this PR and make another push at some point?

**Comment by taylorpapke** [comment]
@TroyFPV48 @Robel-003 sorry to keep bringing this one up but the more I look at, the more I think we should just close this unless there is a major update for it. My reasoning is that it already has conflicts and reverts the variable names we just changed. It's only 7 lines of code so I think we would be better off just making a new branch from main if we wanted to use those lines or pursue the issue that this accomplishes.

**Comment by taylorpapke** [comment]
@TroyFPV48 It looks like we have 1 CodeFactor issue that we have to take care of:
Screenshot 2023-11-05 at 3 00 11 PM
and then we just have to resolve the merge conflicts.
helpful doc for resolving merge conflicts: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by taylorpapke** [comment]
@TroyFPV48 This PR looks like it is targeting the entire user story #67 but doesn't appear to target either of the issues that are within that user story. For instance, navigation bar is not possible yet because it has not been implemented. The only issue that can be worked on for now is the one for better visuals for the heading and font. I suggest we close vs. merge this PR and create separate issues and PR's that relate back to user story #67. @Robel-003 @Seiyaroo

**Comment by taylorpapke** [comment]
Closing this PR with @TroyFPV48's permission. We will create new issues and PR's to relate to user story #67.

**Pull request closed without merging**
