### PR TITLE
nsc-events-adroid_sprint_2_issue_119_navigation_for_signup_page

### PR DESCRIPTION
**Pull request by kkennedy-gh**
Added scaffolding to SignUp.kt in Screen folder for navigation.

Screenshot 2023-11-13 at 1 47 20 PM

### CODE REVIEW

**Comment by bcko** [comment]
@Robel-003 
Feel free to work on this branch or create a new  branch

**Comment by taylorpapke** [comment]
> @Robel-003 Feel free to work on this branch or create a new branch

@Robel-003 while you're here working on this page, can you also update the following:
- make "name" text field 2 fields: "first name" and "last name"
- toggles to make password/confirm password fields visible
- fix keyboard to have an enter key that closes keyboard

We can just carry over what has already been done in Belinda's for this.

**Comment by Robel-003** [comment]
@kkennedy-gh @bcko @taylorpapke Added the scaffolding, the name fields, and password visibility to the page

**Comment by taylorpapke** [comment]
@Robel-003 Tested this and it looks good. One small thing I noticed is that for the last text field, the enter key takes it back to the first text field. I like how it progresses through the other text fields but maybe we could integrate the checkmark button from Belinda's which closes the keyboard on just that last field. If successful, I would like to carry this user friendly enhancement over to Belinda's.

**Review by taylorpapke — APPROVED** [review]

**Review by brinkbrink — APPROVED** [review]
I agree with Taylor. Could you create another issue for that enhancement @Robel-003 ? Otherwise, looks good, will merge.

**Pull request merged**
