### PR TITLE
Nsc events android 4 169 attend button

### PR DESCRIPTION
**Pull request by Exochos**
### Implement Attendance Feature on EventDetailPage

Resolves: [Link to the issue](https://github.com/SeattleColleges/nsc-events-android/issues/97) #169 

Description

This pull request enhances the EventDetailPage by integrating a new feature that allows users to mark their attendance for events. It provides the flexibility to include their name if they wish to the event via a checkbox consent. It also adds a button which explains the consent. 
# OF NOTE: 
Certain values are hard coded right now, 
A) the eventID - currently the value is hard coded from the MongoDB back end running locally.
B) the FirstName and Last name of the user are also hardcoded as they are not yet shared in shared preferences.
 In addition none of the errors or exceptions are actually handled they are just toast messages. 

Features

    Composable Functionality: Developed AttendEvent composable to handle attendance marking with UI state management.
    Attendance Options:

    A)    Named Attendance: Users can opt to provide their first and last names via the UI.
    B)    Anonymous Attendance: Users can mark attendance without providing names. (Default)

Security & Functionality

    Authentication Required: Ensures that only authenticated users can mark attendance.
    User Consent: Users have the option to include their name based on a checkbox consent.
    Toast Messages: Provides real-time feedback to users based on the action's outcome.

Testing

    Manual Testing: Functionality has been manually tested for consistency and responsiveness.
    Toast Feedback: Validated the display of appropriate toast messages on success or failure.
    User Consent: Verified the conditional inclusion of user names based on consent.

### CODE REVIEW

**Comment by kaimanasse15** [comment]
https://youtu.be/HsUxkJ3yBTQ-link check video

**Comment by Exochos** [comment]
> https://youtu.be/HsUxkJ3yBTQ-link check video

?? I can't hear anything and can't understand what is going on?

**Review by taylorpapke — APPROVED** [review]
Looks great!
I'm able to check the box and view the consent:
Screenshot 2024-01-14 at 3 32 13 PM
I'm also able to see the toast message when I click the attend button:
Screenshot 2024-01-14 at 3 32 44 PM

**Review by Robel-003 — APPROVED** [review]
@Exochos This looks great. I can view the consent and I get the same toast message when clicking attend with the "add my name" text box checked. 
I saw the note about having certain fields hardcoded, should we be doing that as well to test this properly?

**Comment by Exochos** [comment]
> @Exochos This looks great. I can view the consent and I get the same toast message when clicking attend with the "add my name" text box checked. I saw the note about having certain fields hardcoded, should we be doing that as well to test this properly?

The value of the eventID will be different for your personal DB until we have a unified backend.

**Pull request merged**
